### ISSUE TITLE
App not available on last firmware update

### ISSUE THREAD

**Issue by juan-sebastian** [LedgerHQ/openpgp-card-app#61]
Hello,

I just updated the firmware of my Ledger Nano X to 1.2.4-5 and I have the bad surprise to discover that the openGPG app is not supported, and I can't revert the process. I not only use my Ledger Nano X to save my crypto assets but also as my authentication device.

Could you please fix this as soon as possible?

Thanks in advance.

**Comment by juan-sebastian** [comment]
Any news regarding this subject? As you can see bellow the app still not available with the last firmware 

![image](https://user-images.githubusercontent.com/36315790/100237721-98e45000-2f2f-11eb-9ab1-21583381dafc.png)

@grydz you are the last committer maybe you can help? 🙂

**Comment by ckahlo** [comment]
Hey there,

same situation here. Wanted to explain a friend how to use OpenPGP.XL and OpenPGP and whats the difference.
He had installed the firmware update and never saw the app, I had started to write code using the OpenPGP app in the past.
Now I installed the new firmware and both OpenPGP and OpenPGP.XL disappered from my ledger and can not be found in
the store.

Sorry Ledger, this is a bit of a mess if functionality suddenly simply disappears after a FW update. For sure I could start to
compile this app on my own, but this a hazzle on our company machines due to enforced security baselines.

Please make those apps available again and WARN us in case you don't have updates in place if you release a FW update.

Best,
Christian

**Comment by TamtamHero** [comment]
Sorry about that, we have some issues with 4096 bits RSA key generation on firmware 1.2.4-5, which blocked the release of this app :grimacing: 
We're trying to solve it, but it will probably require a firmware upgrade. Until then, we're releasing a version of this app without support for4096 bits RSA key generation. 
You should now be able to find it on the store, and I hope you weren't planning on using this exact type of key :see_no_evil: 
About warning users, well... I wish we had some way to do so, I'll talk about it to the Ledger live team.

**Comment by juan-sebastian** [comment]
Thanks a lot, in my case I'm using ed25519 so I'm not impacted by this issue.

**Comment by ckahlo** [comment]
Thank you very much @TamtamHero :-)
I totally understand that and most people nowadays migrate to curves anyway.
So, you helped us a lot with just disabling good ol' RSA4096. :)

Best,
Christian
